In [1]:
import fastf1
import pandas as pd
import numpy as np

In [2]:
#Obtención de todos los circuitos en csv

circuitos = pd.read_csv("../circuits/circuits_2022.csv")
circuitos

,circuitId,url,circuitName,Location/lat,Location/long,Location/locality,Location/country
0,albert_park,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,Albert Park Grand Prix Circuit,-37.8497,144.96800,Melbourne,Australia
1,americas,http://en.wikipedia.org/wiki/Circuit_of_the_Am...,Circuit of the Americas,30.1328,-97.64110,Austin,USA
2,bahrain,http://en.wikipedia.org/wiki/Bahrain_Internati...,Bahrain International Circuit,26.0325,50.51060,Sakhir,Bahrain
3,baku,http://en.wikipedia.org/wiki/Baku_City_Circuit,Baku City Circuit,40.3725,49.85330,Baku,Azerbaijan
4,catalunya,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,Circuit de Barcelona-Catalunya,41.5700,2.26111,Montmeló,Spain
5,hungaroring,http://en.wikipedia.org/wiki/Hungaroring,Hungaroring,47.5789,19.24860,Budapest,Hungary
6,imola,http://en.wikipedia.org/wiki/Autodromo_Enzo_e_...,Autodromo Enzo e Dino Ferrari,44.3439,11.71670,Imola,Italy
7,interlagos,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jo...,Autódromo José Carlos Pace,-23.7036,-46.69970,São Paulo,Brazil
8,jeddah,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...,Jeddah Corniche Circuit,21.6319,39.10440,Jeddah,Saudi Arabia
9,marina_bay,http://en.wikipedia.org/wiki/Marina_Bay_Street...,Marina Bay Street Circuit,1.2914,103.86400,Marina Bay,Singapore
10,miami,http://en.wikipedia.org/wiki/Miami_Internation...,Miami International Autodrome,25.9581,-80.23890,Miami,USA
11,monaco,http://en.wikipedia.org/wiki/Circuit_de_Monaco,Circuit de Monaco,43.7347,7.42056,Monte-Carlo,Monaco
12,monza,http://en.wikipedia.org/wiki/Autodromo_Naziona...,Autodromo Nazionale di Monza,45.6156,9.28111,Monza,Italy
13,red_bull_ring,http://en.wikipedia.org/wiki/Red_Bull_Ring,Red Bull Ring,47.2197,14.76470,Spielberg,Austria
14,ricard,http://en.wikipedia.org/wiki/Paul_Ricard_Circuit,Circuit Paul Ricard,43.2506,5.79167,Le Castellet,France
15,rodriguez,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_He...,Autódromo Hermanos Rodríguez,19.4042,-99.09070,Mexico City,Mexico
16,silverstone,http://en.wikipedia.org/wiki/Silverstone_Circuit,Silverstone Circuit,52.0786,-1.01694,Silverstone,UK
17,spa,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...,Circuit de Spa-Francorchamps,50.4372,5.97139,Spa,Belgium
18,suzuka,http://en.wikipedia.org/wiki/Suzuka_Circuit,Suzuka Circuit,34.8431,136.54100,Suzuka,Japan
19,villeneuve,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...,Circuit Gilles Villeneuve,45.5000,-73.52280,Montreal,Canada
20,yas_marina,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,Yas Marina Circuit,24.4672,54.60310,Abu Dhabi,UAE
21,zandvoort,http://en.wikipedia.org/wiki/Circuit_Zandvoort,Circuit Park Zandvoort,52.3888,4.54092,Zandvoort,Netherlands

In [3]:
#Limpiamos el dataframe de circuitos
print("Circuitos disponibles: ")
circuitos = circuitos.drop(['url', 'Location/lat', 'Location/long', 'Location/locality'], axis = 1)
print(circuitos['Location/country'].to_string(index=False))
nombreCircuito = input("Introduce el pais de un Gran Premio: ")
anyoGp = 2018

Circuitos disponibles:
   Australia
         USA
     Bahrain
  Azerbaijan
       Spain
     Hungary
       Italy
      Brazil
Saudi Arabia
   Singapore
         USA
      Monaco
       Italy
     Austria
      France
      Mexico
          UK
     Belgium
       Japan
      Canada
         UAE
 Netherlands
Introduce el pais de un Gran Premio: Spain

In [4]:
#Creamos un nuevo dataframe con el nombre, la localidad y el nivel de desgaste que pueden tener los neumaticos
circuitos_desgaste = circuitos.drop(['circuitId'], axis=1)
circuitos_desgaste

                       circuitName Location/country
0   Albert Park Grand Prix Circuit        Australia
1          Circuit of the Americas              USA
2    Bahrain International Circuit          Bahrain
3                Baku City Circuit       Azerbaijan
4   Circuit de Barcelona-Catalunya            Spain
5                      Hungaroring          Hungary
6    Autodromo Enzo e Dino Ferrari            Italy
7       Autódromo José Carlos Pace           Brazil
8          Jeddah Corniche Circuit     Saudi Arabia
9        Marina Bay Street Circuit        Singapore
10   Miami International Autodrome              USA
11               Circuit de Monaco           Monaco
12    Autodromo Nazionale di Monza            Italy
13                   Red Bull Ring          Austria
14             Circuit Paul Ricard           France
15    Autódromo Hermanos Rodríguez           Mexico
16             Silverstone Circuit               UK
17    Circuit de Spa-Francorchamps          Belgium
18                  Suzuka Circuit            Japan
19       Circuit Gilles Villeneuve           Canada
20              Yas Marina Circuit              UAE
21          Circuit Park Zandvoort      Netherlands

In [5]:
#Creamos una lista con el nivel de desgaste, fuente PIRELLI F1 2022
desgaste = ['Bajo', 'Alto', 'Alto', 'Bajo', 'Alto', 'Bajo', 'Medio', 'Medio', 'Bajo', 'Bajo', 'Bajo', 'Medio', 'Medio', 'Medio', 'Medio', 'Bajo', 'Medio', 'Alto', 'Medio', 'Bajo', 'Medio', 'Medio']
circuitos_desgaste['desgaste'] = desgaste
circuitos_desgaste
vueltas_circuito = ['58', '56', '57', '51', '66', '70', '63', '71', '50', '61', '57', '78', '53', '71', '53', '71', '52', '44', '53', '70', '58', '72']
circuitos_desgaste['vueltas_totales'] = vueltas_circuito
circuitos_desgaste
km_circuito = ['307.574', '308.405', '308.238', '306.049', '307.104', '306.630', '309.049', '305.879', '308.450', '308.706', '308.326', '260.286', '306.720', '306.452', '309.690', '305.354', '306.198', '308.052', '307.471', '305.270', '305.355', '306.648']
circuitos_desgaste['km_total'] = km_circuito
circuitos_desgaste

#Vamos a sacarlo en un csv
#circuitos_desgaste.to_csv("../circuits/circuitosFinal.csv", index=False)

,circuitName,Location/country,desgaste,vueltas_totales,km_total
0,Albert Park Grand Prix Circuit,Australia,Bajo,58,307.574
1,Circuit of the Americas,USA,Alto,56,308.405
2,Bahrain International Circuit,Bahrain,Alto,57,308.238
3,Baku City Circuit,Azerbaijan,Bajo,51,306.049
4,Circuit de Barcelona-Catalunya,Spain,Alto,66,307.104
5,Hungaroring,Hungary,Bajo,70,306.630
6,Autodromo Enzo e Dino Ferrari,Italy,Medio,63,309.049
7,Autódromo José Carlos Pace,Brazil,Medio,71,305.879
8,Jeddah Corniche Circuit,Saudi Arabia,Bajo,50,308.450
9,Marina Bay Street Circuit,Singapore,Bajo,61,308.706
10,Miami International Autodrome,USA,Bajo,57,308.326
11,Circuit de Monaco,Monaco,Medio,78,260.286
12,Autodromo Nazionale di Monza,Italy,Medio,53,306.720
13,Red Bull Ring,Austria,Medio,71,306.452
14,Circuit Paul Ricard,France,Medio,53,309.690
15,Autódromo Hermanos Rodríguez,Mexico,Bajo,71,305.354
16,Silverstone Circuit,UK,Medio,52,306.198
17,Circuit de Spa-Francorchamps,Belgium,Alto,44,308.052
18,Suzuka Circuit,Japan,Medio,53,307.471
19,Circuit Gilles Villeneuve,Canada,Bajo,70,305.270
20,Yas Marina Circuit,UAE,Medio,58,305.355
21,Circuit Park Zandvoort,Netherlands,Medio,72,306.648

In [6]:
#Vamos entonces a crear un dataframe para un piloto en una determinada 
#carrera, por ejemplo, Fernando Alonso y Monaco 2022
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) #Omitimos los future warning

fastf1.Cache.enable_cache('../cache') # Para cachear los datos y no tener que bajarlos todo el tiempo

#A continuacion, nos guardamos la sesión en una variable de tipo sesion

race = fastf1.get_session(anyoGp, nombreCircuito, 'R')
race.load(weather=True, telemetry= True)

core           INFO 	Loading data for Spanish Grand Prix - Race [v2.3.2]
api            INFO 	Using cached data for driver_info
api            INFO 	Using cached data for timing_data
api            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
api            INFO 	Using cached data for session_status_data
api            INFO 	Using cached data for track_status_data
api            INFO 	Using cached data for car_data
api            INFO 	Using cached data for position_data
api            INFO 	Using cached data for weather_data
api            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '77', '33', '5', '3', '20', '55', '14', '11', '16', '18', '28', '9', '35', '2', '31', '7', '8', '10', '27']

In [7]:
for piloto in race.results['Abbreviation']:
    print(piloto)

HAM
BOT
VER
VET
RIC
MAG
SAI
ALO
PER
LEC
STR
HAR
ERI
SIR
VAN
OCO
RAI
GRO
GAS
HUL

In [143]:
print("Pilotos disponibles: ")
race.results['Abbreviation']
print(race.results['Abbreviation'].to_string(index=False))
nombrePiloto = input("Introduce un piloto: ")

Pilotos disponibles:
HAM
BOT
VER
VET
RIC
MAG
SAI
ALO
PER
LEC
STR
HAR
ERI
SIR
VAN
OCO
RAI
GRO
GAS
HUL
Introduce un piloto: HAM

In [144]:


#Creamos un diccionario para tener los nombres de los pilotos en Ergast y en FastF1 (para poder sacar la posicion por cada vuelta)
#ya que la api tiene la pinta del valor y fastf1 tiene la pinta de la clave (en el diccionario)
pilotosDic = {"HAM":"hamilton", "VER":"max_verstappen", "BOT": "bottas", "NOR":"norris", "PER":"perez", "LEC":"leclerc",
             "RIC":"ricciardo", "SAI":"sainz", "TSU":"tsunoda", "STR":"stroll", "RAI":"raikkonen", "GIO":"giovinazi",
              "OCO":"ocon", "RUS":"russel", "VET":"vettel", "MSC":"mick_schumacher", "GAS":"GASLY", "LAT":"latifi",
             "ALO":"alonso", "MAZ":"mazepin"}
print(pilotosDic[nombrePiloto])

hamilton

In [190]:
#Nos interesa saber el numero de vueltas que dio Alonso en Barcelona 2022


laps_race_pilot = race.laps.pick_driver(nombrePiloto)
weather = race.weather_data # Cogemos tambien el tiempo que hizo al inicio de la carrera
weather

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:33.475000,15.1,55.7,1001.8,False,35.0,84,1.1
1,0 days 00:01:33.488000,15.4,55.1,1001.7,False,35.0,21,1.4
2,0 days 00:02:33.503000,15.3,54.4,1001.6,False,35.0,8,1.5
3,0 days 00:03:33.517000,15.1,54.6,1001.8,False,35.0,62,1.9
4,0 days 00:04:33.531000,15.1,54.4,1001.7,True,35.0,3,1.9
...,...,...,...,...,...,...,...,...
100,0 days 01:40:34.846000,16.9,49.5,1001.5,False,30.7,99,2.3
101,0 days 01:41:34.857000,16.9,49.5,1001.5,False,30.7,99,2.3
102,0 days 01:42:34.871000,16.5,51.2,1001.6,False,29.8,62,2.4
103,0 days 01:43:34.887000,16.0,52.4,1001.7,False,29.1,71,2.2
104,0 days 01:44:34.902000,16.0,53.2,1001.6,True,29.3,77,2.0

In [191]:
laps_race_pilot

,Time,DriverNumber,LapTime,LapNumber,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,...,Compound,TyreLife,FreshTyre,Stint,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,0 days 00:08:52.647000,44,NaT,1.0,0 days 00:00:04.447000,NaT,NaT,0 days 00:00:41.737000,0 days 00:00:39.770000,NaT,...,NaN,NaN,NaN,NaN,0 days 00:07:04.213000,Mercedes,HAM,24,False,2018-05-13 13:13:11.037
1,0 days 00:11:28.349000,44,NaT,2.0,NaT,NaT,0 days 00:01:08.403000,0 days 00:00:45.535000,0 days 00:00:41.852000,0 days 00:10:01.029000,...,NaN,NaN,NaN,NaN,0 days 00:08:52.647000,Mercedes,HAM,4,False,2018-05-13 13:14:59.471
2,0 days 00:13:41.175000,44,0 days 00:02:12.826000,3.0,NaT,NaT,0 days 00:00:45.304000,0 days 00:00:47.505000,0 days 00:00:40.017000,0 days 00:12:13.653000,...,SOFT,4.0,False,1.0,0 days 00:11:28.349000,Mercedes,HAM,4,False,2018-05-13 13:17:35.173
3,0 days 00:15:49.953000,44,0 days 00:02:08.778000,4.0,NaT,NaT,0 days 00:00:40.486000,0 days 00:00:46.974000,0 days 00:00:41.318000,0 days 00:14:21.661000,...,SOFT,5.0,False,1.0,0 days 00:13:41.175000,Mercedes,HAM,4,False,2018-05-13 13:19:47.999
4,0 days 00:18:00.393000,44,0 days 00:02:10.440000,5.0,NaT,NaT,0 days 00:00:43.781000,0 days 00:00:45.934000,0 days 00:00:40.725000,0 days 00:16:33.734000,...,SOFT,6.0,False,1.0,0 days 00:15:49.953000,Mercedes,HAM,4,False,2018-05-13 13:21:56.777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0 days 01:37:15.614000,44,0 days 00:01:19.152000,62.0,NaT,NaT,0 days 00:00:22.689000,0 days 00:00:29.598000,0 days 00:00:26.865000,0 days 01:36:19.151000,...,MEDIUM,37.0,True,2.0,0 days 01:35:56.462000,Mercedes,HAM,1,True,2018-05-13 14:42:03.286
62,0 days 01:38:35.436000,44,0 days 00:01:19.822000,63.0,NaT,NaT,0 days 00:00:22.648000,0 days 00:00:29.851000,0 days 00:00:27.323000,0 days 01:37:38.262000,...,MEDIUM,38.0,True,2.0,0 days 01:37:15.614000,Mercedes,HAM,1,True,2018-05-13 14:43:22.438
63,0 days 01:39:54.569000,44,0 days 00:01:19.133000,64.0,NaT,NaT,0 days 00:00:22.423000,0 days 00:00:29.626000,0 days 00:00:27.084000,0 days 01:38:57.859000,...,MEDIUM,39.0,True,2.0,0 days 01:38:35.436000,Mercedes,HAM,1,True,2018-05-13 14:44:42.260
64,0 days 01:41:14.010000,44,0 days 00:01:19.425000,65.0,NaT,NaT,NaT,0 days 00:00:29.990000,0 days 00:00:27.012000,NaT,...,MEDIUM,40.0,True,2.0,0 days 01:39:54.569000,Mercedes,HAM,1,False,2018-05-13 14:46:01.393
65,0 days 01:42:34.403000,44,0 days 00:01:20.393000,66.0,NaT,NaT,0 days 00:00:22.554000,0 days 00:00:29.644000,0 days 00:00:28.195000,0 days 01:41:36.564000,...,MEDIUM,41.0,True,2.0,0 days 01:41:14.010000,Mercedes,HAM,1,True,2018-05-13 14:47:20.834

In [192]:
#Limpiamos el dataset con solo lo que nos interesa

laps_race_pilot = laps_race_pilot.filter(['Time', 'LapTime', 'LapNumber', 'Compound', 'TyreLife', 'FreshTyre', 'TrackStatus', 'Stint', 'PitInTime'])
laps_race_pilot

,Time,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime
0,0 days 00:08:52.647000,NaT,1.0,NaN,NaN,NaN,24,NaN,NaT
1,0 days 00:11:28.349000,NaT,2.0,NaN,NaN,NaN,4,NaN,NaT
2,0 days 00:13:41.175000,0 days 00:02:12.826000,3.0,SOFT,4.0,False,4,1.0,NaT
3,0 days 00:15:49.953000,0 days 00:02:08.778000,4.0,SOFT,5.0,False,4,1.0,NaT
4,0 days 00:18:00.393000,0 days 00:02:10.440000,5.0,SOFT,6.0,False,4,1.0,NaT
...,...,...,...,...,...,...,...,...,...
61,0 days 01:37:15.614000,0 days 00:01:19.152000,62.0,MEDIUM,37.0,True,1,2.0,NaT
62,0 days 01:38:35.436000,0 days 00:01:19.822000,63.0,MEDIUM,38.0,True,1,2.0,NaT
63,0 days 01:39:54.569000,0 days 00:01:19.133000,64.0,MEDIUM,39.0,True,1,2.0,NaT
64,0 days 01:41:14.010000,0 days 00:01:19.425000,65.0,MEDIUM,40.0,True,1,2.0,NaT
65,0 days 01:42:34.403000,0 days 00:01:20.393000,66.0,MEDIUM,41.0,True,1,2.0,NaT

In [193]:
#De aqui solo queremos la temperatura de la pista, la temperatura ambiente y si llovía o no 
#Importante, hacemos match de la columna time, o ponemos simplemente el tiempo que hacia en la salida????
weather = weather.filter(['Time', 'AirTemp', 'Humidity', 'Rainfall', 'TrackTemp'])
weather

                      Time  AirTemp  Humidity  Rainfall  TrackTemp
0   0 days 00:00:33.475000     15.1      55.7     False       35.0
1   0 days 00:01:33.488000     15.4      55.1     False       35.0
2   0 days 00:02:33.503000     15.3      54.4     False       35.0
3   0 days 00:03:33.517000     15.1      54.6     False       35.0
4   0 days 00:04:33.531000     15.1      54.4      True       35.0
..                     ...      ...       ...       ...        ...
100 0 days 01:40:34.846000     16.9      49.5     False       30.7
101 0 days 01:41:34.857000     16.9      49.5     False       30.7
102 0 days 01:42:34.871000     16.5      51.2     False       29.8
103 0 days 01:43:34.887000     16.0      52.4     False       29.1
104 0 days 01:44:34.902000     16.0      53.2      True       29.3

[105 rows x 5 columns]

In [194]:
weather['Time'] = weather['Time'].astype(str)
weather

                       Time  AirTemp  Humidity  Rainfall  TrackTemp
0    0 days 00:00:33.475000     15.1      55.7     False       35.0
1    0 days 00:01:33.488000     15.4      55.1     False       35.0
2    0 days 00:02:33.503000     15.3      54.4     False       35.0
3    0 days 00:03:33.517000     15.1      54.6     False       35.0
4    0 days 00:04:33.531000     15.1      54.4      True       35.0
..                      ...      ...       ...       ...        ...
100  0 days 01:40:34.846000     16.9      49.5     False       30.7
101  0 days 01:41:34.857000     16.9      49.5     False       30.7
102  0 days 01:42:34.871000     16.5      51.2     False       29.8
103  0 days 01:43:34.887000     16.0      52.4     False       29.1
104  0 days 01:44:34.902000     16.0      53.2      True       29.3

[105 rows x 5 columns]

In [195]:
#Modificamos la columna de Time, para que solo nos muestre la hora y el minuto, esto es para
#que casen las keys al hacer el join y podamos tener info de la temperatura minuto a minuto en las vueltas
weather['Time'] = weather["Time"].apply(lambda x: x[7:12])
weather

      Time  AirTemp  Humidity  Rainfall  TrackTemp
0    00:00     15.1      55.7     False       35.0
1    00:01     15.4      55.1     False       35.0
2    00:02     15.3      54.4     False       35.0
3    00:03     15.1      54.6     False       35.0
4    00:04     15.1      54.4      True       35.0
..     ...      ...       ...       ...        ...
100  01:40     16.9      49.5     False       30.7
101  01:41     16.9      49.5     False       30.7
102  01:42     16.5      51.2     False       29.8
103  01:43     16.0      52.4     False       29.1
104  01:44     16.0      53.2      True       29.3

[105 rows x 5 columns]

In [196]:
#Hacemos lo mismo para la columa Time de las vueltas
laps_race_pilot['Time'] = laps_race_pilot['Time'].astype(str)
laps_race_pilot['Time'] = laps_race_pilot["Time"].apply(lambda x: x[7:12])
laps_race_pilot

,Time,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime
0,00:08,NaT,1.0,NaN,NaN,NaN,24,NaN,NaT
1,00:11,NaT,2.0,NaN,NaN,NaN,4,NaN,NaT
2,00:13,0 days 00:02:12.826000,3.0,SOFT,4.0,False,4,1.0,NaT
3,00:15,0 days 00:02:08.778000,4.0,SOFT,5.0,False,4,1.0,NaT
4,00:18,0 days 00:02:10.440000,5.0,SOFT,6.0,False,4,1.0,NaT
...,...,...,...,...,...,...,...,...,...
61,01:37,0 days 00:01:19.152000,62.0,MEDIUM,37.0,True,1,2.0,NaT
62,01:38,0 days 00:01:19.822000,63.0,MEDIUM,38.0,True,1,2.0,NaT
63,01:39,0 days 00:01:19.133000,64.0,MEDIUM,39.0,True,1,2.0,NaT
64,01:41,0 days 00:01:19.425000,65.0,MEDIUM,40.0,True,1,2.0,NaT
65,01:42,0 days 00:01:20.393000,66.0,MEDIUM,41.0,True,1,2.0,NaT

In [197]:
#Hacemos el join para meter en el mismo dataset, la imformacion en cada vuelta de la temperatura ambiente y de la pista

laps_race_pilot = laps_race_pilot.set_index('Time').join(weather.set_index('Time'))

In [198]:
laps_race_pilot['LapTime'] = laps_race_pilot['LapTime'].astype(str)
laps_race_pilot["LapTime"] = laps_race_pilot["LapTime"].apply(lambda x: x[10:19] if x!="NaT" else '0')
laps_race_pilot

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime,AirTemp,Humidity,Rainfall,TrackTemp
Time,,,,,,,,,,,,
00:08,0,1.0,NaN,NaN,NaN,24,NaN,NaT,15.3,54.1,False,35.0
00:11,0,2.0,NaN,NaN,NaN,4,NaN,NaT,16.0,52.9,True,35.0
00:13,02:12.826,3.0,SOFT,4.0,False,4,1.0,NaT,16.3,51.0,True,35.6
00:15,02:08.778,4.0,SOFT,5.0,False,4,1.0,NaT,15.9,52.0,True,34.0
00:18,02:10.440,5.0,SOFT,6.0,False,4,1.0,NaT,16.1,52.4,True,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...
01:37,01:19.152,62.0,MEDIUM,37.0,True,1,2.0,NaT,17.0,50.1,False,32.3
01:38,01:19.822,63.0,MEDIUM,38.0,True,1,2.0,NaT,17.1,49.6,False,31.6
01:39,01:19.133,64.0,MEDIUM,39.0,True,1,2.0,NaT,17.0,49.5,False,30.9
01:41,01:19.425,65.0,MEDIUM,40.0,True,1,2.0,NaT,16.9,49.5,False,30.7
01:42,01:20.393,66.0,MEDIUM,41.0,True,1,2.0,NaT,16.5,51.2,False,29.8

In [199]:
#Para la posicion de salida
#posicion_salida = race.get_driver(nombrePiloto)['GridPosition']
#posicion_salida
race.get_driver(nombrePiloto)

DriverNumber                         44
BroadcastName                L HAMILTON
Abbreviation                        HAM
TeamName                       Mercedes
TeamColor                        00D2BE
FirstName                         Lewis
LastName                       Hamilton
FullName                 Lewis Hamilton
Position                            1.0
GridPosition                        1.0
Q1                                  NaT
Q2                                  NaT
Q3                                  NaT
Time             0 days 01:35:29.972000
Status                         Finished
Points                             25.0
Name: Lewis, dtype: object

In [200]:
#Necesitamos ahora los outputs, que es la siguiente vuelta a parar
vueltas_parada = laps_race_pilot[laps_race_pilot['PitInTime'].notna()]
vueltas_parada

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime,AirTemp,Humidity,Rainfall,TrackTemp
Time,,,,,,,,,,,,
00:46,01:24.565,25.0,SOFT,26.0,False,1,1.0,0 days 00:46:04.600000,15.8,53.5,True,29.7

In [201]:
nVuelta_parada = vueltas_parada['LapNumber']
nParadas = 0
paradas = []
for i in nVuelta_parada:
    paradas.append(i)
    nParadas = nParadas + 1


print("El numero de paradas ha sido: ", nParadas)

print("Las paradas han sido en las vueltas: ", paradas)

El numero de paradas ha sido:  1
Las paradas han sido en las vueltas:  [25.0]

In [202]:
#Eliminanos la variable de la hora a la que entra a box porque ya no es necesaria
laps_race_pilot.drop(['PitInTime'], axis = 1, inplace=True)
#laps_race_pilot.drop(laps_race_pilot[(laps_race_pilot['LapTime'] =='0') & (laps_race_pilot['LapNumber'] != 1)].index, inplace=True)
laps_race_pilot

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,AirTemp,Humidity,Rainfall,TrackTemp
Time,,,,,,,,,,,
00:08,0,1.0,NaN,NaN,NaN,24,NaN,15.3,54.1,False,35.0
00:11,0,2.0,NaN,NaN,NaN,4,NaN,16.0,52.9,True,35.0
00:13,02:12.826,3.0,SOFT,4.0,False,4,1.0,16.3,51.0,True,35.6
00:15,02:08.778,4.0,SOFT,5.0,False,4,1.0,15.9,52.0,True,34.0
00:18,02:10.440,5.0,SOFT,6.0,False,4,1.0,16.1,52.4,True,36.2
...,...,...,...,...,...,...,...,...,...,...,...
01:37,01:19.152,62.0,MEDIUM,37.0,True,1,2.0,17.0,50.1,False,32.3
01:38,01:19.822,63.0,MEDIUM,38.0,True,1,2.0,17.1,49.6,False,31.6
01:39,01:19.133,64.0,MEDIUM,39.0,True,1,2.0,17.0,49.5,False,30.9
01:41,01:19.425,65.0,MEDIUM,40.0,True,1,2.0,16.9,49.5,False,30.7
01:42,01:20.393,66.0,MEDIUM,41.0,True,1,2.0,16.5,51.2,False,29.8

In [203]:
nVueltasDadas = int(laps_race_pilot.tail(1)['LapNumber'].iloc[0])
nVueltasDadas

66

In [204]:
#Ahora hay que añadir al dataframe las variables
# - Posicion de salida
# - Siguiente parada (dependera de la vuelta en la que se encuentre)
# - Todas variables del circuito en el que nos encontramos, en este caso Barcelona
# - No creo que haga falta el piloto, las estrategias son independientes del piloto (o eso voy a pensar... que no será asi)
circuito_actual = circuitos_desgaste.loc[circuitos_desgaste['Location/country'].str.lower() == nombreCircuito.lower()]
circuito_actual = circuito_actual.filter(['circuitName', 'desgaste', 'vueltas_totales', 'km_total'])
circuito_actual
vueltasOficialesCircuito = circuito_actual['vueltas_totales'].iloc[0]
print(vueltasOficialesCircuito)
print(nVueltasDadas)
disminuido = False

if (str(nVueltasDadas) != vueltasOficialesCircuito):
    nVueltasDadas = nVueltasDadas -1
    disminuido = True

print("Las vueltas son: " + str(nVueltasDadas))

66
66
Las vueltas son: 66

In [205]:
#Ahora hay que introducir la columna posicionActual que es la posicion que ocupa un piloto por cada paso por meta3#
#para cada una de las vueltas que un piloto dio en un determinado gran premio
#Para elllo hay que construir la llamada a la API de Ergast, que tiene esta pinta:
# http://ergast.com/api/f1/2022/1/drivers/alonso/laps/19
#Necesitamos el numero de ronda, el año del gp, el numero de vuelta y el nombre del piloto
import requests
import json
import time
roundNumber = race.event.RoundNumber
pilotoNombre=pilotosDic[nombrePiloto]
posicionesList = []
pilotoDelanteList = []
tiempoPilotoDelanteList = []
pilotoDetrasList = []
tiempoPilotoDetrasList = []


#Llamada a api de posiciones
api = "http://ergast.com/api/f1/" + str(anyoGp) + "/" + str(roundNumber) + "/drivers/" +pilotoNombre + "/laps.json?limit=100"
response = requests.get(api)
posiciones_dict = json.loads(response.text)
#Llamada a api de pilotos y tiempo
api = "http://ergast.com/api/f1/" + str(anyoGp) + "/" + str(roundNumber) + "/" + "laps.json?limit=4000"
response = requests.get(api)
pilotos_dict = json.loads(response.text)
    
#El numero de vuelta es una iteracion a cada fila dell dataframe de vueltas del piloto

for nVuelta in range (0, nVueltasDadas):
    print(nVuelta, nVueltasDadas)
    #Para la posicion por cada vuelta
    posicion = posiciones_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][0]['position']
    posicionesList.append(posicion)

    #Para el piloto de delante y su tiempo en cada vuelta
    pilotoDelante = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)-2]['driverId']
    tiempoPilotoDelante = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)-2]['time']
    pilotoDelanteList.append(pilotoDelante)
    tiempoPilotoDelanteList.append(tiempoPilotoDelante)
    print("Voy el: ", posicion)  
    print("Tengo delante a : ", pilotoDelante)  

    #Para el piloto de detras y su tiempo en cada vuelta
    pilotoDetras = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)]['driverId']
    tiempoPilotoDetras = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)]['time']
    pilotoDetrasList.append(pilotoDetras)
    tiempoPilotoDetrasList.append(tiempoPilotoDetras)  
    print("Tengo detras a : ", pilotoDetras)  



if (disminuido):
    posicionesList.append("NaN")
    pilotoDelanteList.append("NaN")
    tiempoPilotoDelanteList.append("NaN")
    pilotoDetrasList.append("NaN")
    tiempoPilotoDetrasList.append("NaN")

laps_race_pilot['posicionActual'] = posicionesList
laps_race_pilot['pilotoDelante'] = pilotoDelanteList
laps_race_pilot['tiempoPilotoDelante'] = tiempoPilotoDelanteList
laps_race_pilot['pilotoDetras'] = pilotoDetrasList
laps_race_pilot['tiempoPilotoDetras'] = tiempoPilotoDetrasList


laps_race_pilot

0 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
1 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
2 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
3 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
4 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
5 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
6 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
7 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
8 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
9 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
10 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
11 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
12 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
13 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
14 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
15 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  vettel
16 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  bottas
17 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  bottas
18 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  bottas
19 66
Voy el:  1
Tengo delante a :  brendon_hartley
Tengo detras a :  raikkonen
20 66
Voy el:  1
Tengo delante a :  stroll
Tengo detras a :  raikkonen
21 66
Voy el:  1
Tengo delante a :  stroll
Tengo detras a :  raikkonen
22 66
Voy el:  1
Tengo delante a :  stroll
Tengo detras a :  raikkonen
23 66
Voy el:  1
Tengo delante a :  stroll
Tengo detras a :  max_verstappen
24 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  max_verstappen
25 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
26 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
27 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
28 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
29 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
30 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
31 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
32 66
Voy el:  2
Tengo delante a :  max_verstappen
Tengo detras a :  ricciardo
33 66
Voy el:  1
Tengo delante a :  ocon
Tengo detras a :  max_verstappen
34 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
35 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
36 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
37 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
38 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
39 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
40 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  vettel
41 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
42 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
43 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
44 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
45 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
46 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
47 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
48 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
49 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
50 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
51 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
52 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
53 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
54 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
55 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
56 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
57 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
58 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
59 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
60 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
61 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
62 66
Voy el:  1
Tengo delante a :  sirotkin
Tengo detras a :  bottas
63 66
Voy el:  1
Tengo delante a :  ericsson
Tengo detras a :  bottas
64 66
Voy el:  1
Tengo delante a :  alonso
Tengo detras a :  bottas
65 66
Voy el:  1
Tengo delante a :  ricciardo
Tengo detras a :  bottas

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,AirTemp,Humidity,Rainfall,TrackTemp,posicionActual,pilotoDelante,tiempoPilotoDelante,pilotoDetras,tiempoPilotoDetras
Time,,,,,,,,,,,,,,,,
00:08,0,1.0,NaN,NaN,NaN,24,NaN,15.3,54.1,False,35.0,1,sirotkin,2:15.710,vettel,1:49.029
00:11,0,2.0,NaN,NaN,NaN,4,NaN,16.0,52.9,True,35.0,1,sirotkin,2:29.412,vettel,2:36.045
00:13,02:12.826,3.0,SOFT,4.0,False,4,1.0,16.3,51.0,True,35.6,1,sirotkin,2:14.646,vettel,2:13.906
00:15,02:08.778,4.0,SOFT,5.0,False,4,1.0,15.9,52.0,True,34.0,1,sirotkin,2:13.632,vettel,2:08.681
00:18,02:10.440,5.0,SOFT,6.0,False,4,1.0,16.1,52.4,True,36.2,1,sirotkin,2:07.410,vettel,2:09.827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01:37,01:19.152,62.0,MEDIUM,37.0,True,1,2.0,17.0,50.1,False,32.3,1,sirotkin,1:24.779,bottas,1:19.872
01:38,01:19.822,63.0,MEDIUM,38.0,True,1,2.0,17.1,49.6,False,31.6,1,sirotkin,1:23.323,bottas,1:20.058
01:39,01:19.133,64.0,MEDIUM,39.0,True,1,2.0,17.0,49.5,False,30.9,1,ericsson,1:24.541,bottas,1:20.421
01:41,01:19.425,65.0,MEDIUM,40.0,True,1,2.0,16.9,49.5,False,30.7,1,alonso,1:21.059,bottas,1:21.130
01:42,01:20.393,66.0,MEDIUM,41.0,True,1,2.0,16.5,51.2,False,29.8,1,ricciardo,1:21.678,bottas,1:20.478

In [206]:
roundNumber

5

In [207]:
import math

In [208]:
#Hay que hacer una funcion para sacar el numero de vueltas (nVueltas) que se ha dado en ese circuito, y repetir nVueltas para crear una lista con el valor
nVueltasCircuito=laps_race_pilot.tail(1).LapNumber.values[0]
circuitName = circuito_actual.circuitName.values[0]
desgaste = circuito_actual.desgaste.values[0]
km_total = circuito_actual.km_total.values[0]
vueltas_totales = circuito_actual.vueltas_totales.values[0]
desgaste
print(nVueltasCircuito)

66.0

In [209]:
posicion_salida = race.get_driver(nombrePiloto)['GridPosition']

#La salida se la tenemos que meter a todas las filas del dataframe
laps_race_pilot['posicionSalida'] = posicion_salida
laps_race_pilot.insert(1,"anyo",anyoGp,False)
#laps_race_pilot['circuitName'] = circuitName
#laps_race_pilot['desgasteCircuito'] = desgaste
#laps_race_pilot['vueltasCircuito'] = vueltas_totales
#laps_race_pilot['kmCircuitoTotales'] = km_total

laps_race_pilot

,LapTime,anyo,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,AirTemp,Humidity,Rainfall,TrackTemp,posicionActual,pilotoDelante,tiempoPilotoDelante,pilotoDetras,tiempoPilotoDetras,posicionSalida
Time,,,,,,,,,,,,,,,,,,
00:08,0,2018,1.0,NaN,NaN,NaN,24,NaN,15.3,54.1,False,35.0,1,sirotkin,2:15.710,vettel,1:49.029,1.0
00:11,0,2018,2.0,NaN,NaN,NaN,4,NaN,16.0,52.9,True,35.0,1,sirotkin,2:29.412,vettel,2:36.045,1.0
00:13,02:12.826,2018,3.0,SOFT,4.0,False,4,1.0,16.3,51.0,True,35.6,1,sirotkin,2:14.646,vettel,2:13.906,1.0
00:15,02:08.778,2018,4.0,SOFT,5.0,False,4,1.0,15.9,52.0,True,34.0,1,sirotkin,2:13.632,vettel,2:08.681,1.0
00:18,02:10.440,2018,5.0,SOFT,6.0,False,4,1.0,16.1,52.4,True,36.2,1,sirotkin,2:07.410,vettel,2:09.827,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01:37,01:19.152,2018,62.0,MEDIUM,37.0,True,1,2.0,17.0,50.1,False,32.3,1,sirotkin,1:24.779,bottas,1:19.872,1.0
01:38,01:19.822,2018,63.0,MEDIUM,38.0,True,1,2.0,17.1,49.6,False,31.6,1,sirotkin,1:23.323,bottas,1:20.058,1.0
01:39,01:19.133,2018,64.0,MEDIUM,39.0,True,1,2.0,17.0,49.5,False,30.9,1,ericsson,1:24.541,bottas,1:20.421,1.0
01:41,01:19.425,2018,65.0,MEDIUM,40.0,True,1,2.0,16.9,49.5,False,30.7,1,alonso,1:21.059,bottas,1:21.130,1.0
01:42,01:20.393,2018,66.0,MEDIUM,41.0,True,1,2.0,16.5,51.2,False,29.8,1,ricciardo,1:21.678,bottas,1:20.478,1.0

In [210]:
#Ahora hay que meter las paradas, habria que añadir una columna con la siguiente parada, dependiendo de la vuelta en la que se encuentre
paradas_list = paradas
paradas_list

[25.0]

In [211]:
nVueltasCircuito

66.0

In [212]:
#En cada intervalo de ventana de parada, se añade la siguiente parada de acuerdo con el numero de vuelta en el que vamos
#Es decir, del intervalo 1-9, el valor de la siguiente parada es 10, del 10-30, el valor es 31, y así
#NOTA: Cuando se hace la ultima parada, ¿cual debe ser el valor del la siguiente parada? ¿El numero de fin de vuelta?


inserciones = 1
paradasList_insertar = []
for i in paradas_list:
        while (inserciones <= i):
            paradasList_insertar.append(i)
            inserciones = inserciones + 1
            if (inserciones == paradas_list[nParadas-1]):
                while inserciones <= nVueltasCircuito:
                    paradasList_insertar.append(nVueltasCircuito)
                    inserciones = inserciones + 1
paradasList_insertar
len(paradasList_insertar)

66

In [213]:
len(laps_race_pilot)

66

In [214]:
#Insertamos la nueva columna
laps_race_pilot['nextPit'] = paradasList_insertar
laps_race_pilot

,LapTime,anyo,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,AirTemp,Humidity,Rainfall,TrackTemp,posicionActual,pilotoDelante,tiempoPilotoDelante,pilotoDetras,tiempoPilotoDetras,posicionSalida,nextPit
Time,,,,,,,,,,,,,,,,,,,
00:08,0,2018,1.0,NaN,NaN,NaN,24,NaN,15.3,54.1,False,35.0,1,sirotkin,2:15.710,vettel,1:49.029,1.0,25.0
00:11,0,2018,2.0,NaN,NaN,NaN,4,NaN,16.0,52.9,True,35.0,1,sirotkin,2:29.412,vettel,2:36.045,1.0,25.0
00:13,02:12.826,2018,3.0,SOFT,4.0,False,4,1.0,16.3,51.0,True,35.6,1,sirotkin,2:14.646,vettel,2:13.906,1.0,25.0
00:15,02:08.778,2018,4.0,SOFT,5.0,False,4,1.0,15.9,52.0,True,34.0,1,sirotkin,2:13.632,vettel,2:08.681,1.0,25.0
00:18,02:10.440,2018,5.0,SOFT,6.0,False,4,1.0,16.1,52.4,True,36.2,1,sirotkin,2:07.410,vettel,2:09.827,1.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01:37,01:19.152,2018,62.0,MEDIUM,37.0,True,1,2.0,17.0,50.1,False,32.3,1,sirotkin,1:24.779,bottas,1:19.872,1.0,66.0
01:38,01:19.822,2018,63.0,MEDIUM,38.0,True,1,2.0,17.1,49.6,False,31.6,1,sirotkin,1:23.323,bottas,1:20.058,1.0,66.0
01:39,01:19.133,2018,64.0,MEDIUM,39.0,True,1,2.0,17.0,49.5,False,30.9,1,ericsson,1:24.541,bottas,1:20.421,1.0,66.0
01:41,01:19.425,2018,65.0,MEDIUM,40.0,True,1,2.0,16.9,49.5,False,30.7,1,alonso,1:21.059,bottas,1:21.130,1.0,66.0
01:42,01:20.393,2018,66.0,MEDIUM,41.0,True,1,2.0,16.5,51.2,False,29.8,1,ricciardo,1:21.678,bottas,1:20.478,1.0,66.0

En principio, ahora tenemos el dataset para:

- Un piloto
- En un gran premio
- Durante todas sus vueltas

## Agregamos la columna de si ha hecho pit o no, esto es una aproximacion a nuestro problema

In [215]:
lista = []
anterior = 1
for valor in laps_race_pilot['Stint']:
    if (valor == anterior) or (math.isnan(valor)):
        lista.append(0)
    else:
        lista.append(1)
    anterior = valor
try:
    laps_race_pilot.insert(8, "makeStop", lista, False)
except:
  print("No se ha podido añadir, ya existe")

laps_race_pilot[:30]

,LapTime,anyo,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,makeStop,AirTemp,Humidity,Rainfall,TrackTemp,posicionActual,pilotoDelante,tiempoPilotoDelante,pilotoDetras,tiempoPilotoDetras,posicionSalida,nextPit
Time,,,,,,,,,,,,,,,,,,,,
00:08,0,2018,1.0,NaN,NaN,NaN,24,NaN,0,15.3,54.1,False,35.0,1,sirotkin,2:15.710,vettel,1:49.029,1.0,25.0
00:11,0,2018,2.0,NaN,NaN,NaN,4,NaN,0,16.0,52.9,True,35.0,1,sirotkin,2:29.412,vettel,2:36.045,1.0,25.0
00:13,02:12.826,2018,3.0,SOFT,4.0,False,4,1.0,1,16.3,51.0,True,35.6,1,sirotkin,2:14.646,vettel,2:13.906,1.0,25.0
00:15,02:08.778,2018,4.0,SOFT,5.0,False,4,1.0,0,15.9,52.0,True,34.0,1,sirotkin,2:13.632,vettel,2:08.681,1.0,25.0
00:18,02:10.440,2018,5.0,SOFT,6.0,False,4,1.0,0,16.1,52.4,True,36.2,1,sirotkin,2:07.410,vettel,2:09.827,1.0,25.0
00:20,02:13.880,2018,6.0,SOFT,7.0,False,4,1.0,0,16.7,51.5,False,36.6,1,sirotkin,1:59.521,vettel,2:13.232,1.0,25.0
00:21,01:22.990,2018,7.0,SOFT,8.0,False,1,1.0,0,16.4,50.3,False,36.7,1,brendon_hartley,1:30.479,vettel,1:23.604,1.0,25.0
00:22,01:21.631,2018,8.0,SOFT,9.0,False,1,1.0,0,16.3,50.9,False,36.7,1,brendon_hartley,1:26.554,vettel,1:22.259,1.0,25.0
00:24,01:21.386,2018,9.0,SOFT,10.0,False,1,1.0,0,16.3,51.4,True,35.4,1,brendon_hartley,1:25.665,vettel,1:22.475,1.0,25.0
00:25,01:21.790,2018,10.0,SOFT,11.0,False,1,1.0,0,16.2,51.0,True,35.1,1,brendon_hartley,1:25.523,vettel,1:22.536,1.0,25.0
00:27,01:21.808,2018,11.0,SOFT,12.0,False,1,1.0,0,16.4,52.4,True,35.7,1,brendon_hartley,1:25.151,vettel,1:22.300,1.0,25.0
00:28,01:21.810,2018,12.0,SOFT,13.0,False,1,1.0,0,16.6,50.7,True,36.3,1,brendon_hartley,1:24.969,vettel,1:22.875,1.0,25.0
00:29,01:21.936,2018,13.0,SOFT,14.0,False,1,1.0,0,16.5,50.2,True,35.8,1,brendon_hartley,1:25.515,vettel,1:22.320,1.0,25.0
00:31,01:21.574,2018,14.0,SOFT,15.0,False,1,1.0,0,16.4,51.8,True,33.2,1,brendon_hartley,1:25.890,vettel,1:22.162,1.0,25.0
00:32,01:21.778,2018,15.0,SOFT,16.0,False,1,1.0,0,16.2,51.6,True,32.6,1,brendon_hartley,1:24.707,vettel,1:22.231,1.0,25.0
00:33,01:21.562,2018,16.0,SOFT,17.0,False,1,1.0,0,16.1,51.2,True,32.5,1,brendon_hartley,1:24.086,vettel,1:22.043,1.0,25.0
00:35,01:21.509,2018,17.0,SOFT,18.0,False,1,1.0,0,16.0,51.9,True,31.8,1,brendon_hartley,1:24.194,bottas,1:21.956,1.0,25.0
00:36,01:21.328,2018,18.0,SOFT,19.0,False,1,1.0,0,15.8,52.8,True,31.4,1,brendon_hartley,1:24.529,bottas,1:21.485,1.0,25.0
00:37,01:21.393,2018,19.0,SOFT,20.0,False,1,1.0,0,15.9,52.8,True,31.1,1,brendon_hartley,1:24.758,bottas,1:24.219,1.0,25.0
00:39,01:21.334,2018,20.0,SOFT,21.0,False,1,1.0,0,15.8,53.8,True,30.8,1,brendon_hartley,1:24.331,raikkonen,1:21.993,1.0,25.0
00:40,01:21.157,2018,21.0,SOFT,22.0,False,1,1.0,0,15.9,53.3,True,30.6,1,stroll,1:41.230,raikkonen,1:21.963,1.0,25.0
00:42,01:20.849,2018,22.0,SOFT,23.0,False,1,1.0,0,15.7,52.8,False,29.7,1,stroll,1:23.280,raikkonen,1:21.946,1.0,25.0
00:43,01:21.045,2018,23.0,SOFT,24.0,False,1,1.0,0,15.7,53.3,True,30.2,1,stroll,1:25.187,raikkonen,1:21.531,1.0,25.0
00:44,01:21.662,2018,24.0,SOFT,25.0,False,1,1.0,0,15.7,53.2,True,30.2,1,stroll,1:23.537,max_verstappen,1:22.241,1.0,25.0
00:46,01:24.565,2018,25.0,SOFT,26.0,False,1,1.0,0,15.8,53.5,True,29.7,1,sirotkin,1:43.641,max_verstappen,1:21.290,1.0,66.0
00:47,01:40.689,2018,26.0,MEDIUM,1.0,True,1,2.0,1,15.8,53.2,True,29.6,2,max_verstappen,1:21.192,ricciardo,1:22.592,1.0,66.0
00:49,01:20.131,2018,27.0,MEDIUM,2.0,True,1,2.0,0,15.8,53.7,True,29.3,2,max_verstappen,1:21.370,ricciardo,1:22.008,1.0,66.0
00:50,01:20.711,2018,28.0,MEDIUM,3.0,True,1,2.0,0,15.9,53.3,True,29.6,2,max_verstappen,1:20.603,ricciardo,1:22.041,1.0,66.0
00:51,01:20.713,2018,29.0,MEDIUM,4.0,True,1,2.0,0,15.7,53.3,True,29.6,2,max_verstappen,1:21.396,ricciardo,1:22.459,1.0,66.0
00:53,01:21.074,2018,30.0,MEDIUM,5.0,True,1,2.0,0,15.6,53.8,True,29.0,2,max_verstappen,1:21.372,ricciardo,1:21.403,1.0,66.0