In [267]:
import fastf1
import pandas as pd
import numpy as np

In [268]:
#Obtención de todos los circuitos en csv

circuitos = pd.read_csv("../circuits/circuits_2022.csv")
circuitos

,circuitId,url,circuitName,Location/lat,Location/long,Location/locality,Location/country
0,albert_park,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,Albert Park Grand Prix Circuit,-37.8497,144.96800,Melbourne,Australia
1,americas,http://en.wikipedia.org/wiki/Circuit_of_the_Am...,Circuit of the Americas,30.1328,-97.64110,Austin,USA
2,bahrain,http://en.wikipedia.org/wiki/Bahrain_Internati...,Bahrain International Circuit,26.0325,50.51060,Sakhir,Bahrain
3,baku,http://en.wikipedia.org/wiki/Baku_City_Circuit,Baku City Circuit,40.3725,49.85330,Baku,Azerbaijan
4,catalunya,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,Circuit de Barcelona-Catalunya,41.5700,2.26111,Montmeló,Spain
5,hungaroring,http://en.wikipedia.org/wiki/Hungaroring,Hungaroring,47.5789,19.24860,Budapest,Hungary
6,imola,http://en.wikipedia.org/wiki/Autodromo_Enzo_e_...,Autodromo Enzo e Dino Ferrari,44.3439,11.71670,Imola,Italy
7,interlagos,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jo...,Autódromo José Carlos Pace,-23.7036,-46.69970,São Paulo,Brazil
8,jeddah,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...,Jeddah Corniche Circuit,21.6319,39.10440,Jeddah,Saudi Arabia
9,marina_bay,http://en.wikipedia.org/wiki/Marina_Bay_Street...,Marina Bay Street Circuit,1.2914,103.86400,Marina Bay,Singapore
10,miami,http://en.wikipedia.org/wiki/Miami_Internation...,Miami International Autodrome,25.9581,-80.23890,Miami,USA
11,monaco,http://en.wikipedia.org/wiki/Circuit_de_Monaco,Circuit de Monaco,43.7347,7.42056,Monte-Carlo,Monaco
12,monza,http://en.wikipedia.org/wiki/Autodromo_Naziona...,Autodromo Nazionale di Monza,45.6156,9.28111,Monza,Italy
13,red_bull_ring,http://en.wikipedia.org/wiki/Red_Bull_Ring,Red Bull Ring,47.2197,14.76470,Spielberg,Austria
14,ricard,http://en.wikipedia.org/wiki/Paul_Ricard_Circuit,Circuit Paul Ricard,43.2506,5.79167,Le Castellet,France
15,rodriguez,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_He...,Autódromo Hermanos Rodríguez,19.4042,-99.09070,Mexico City,Mexico
16,silverstone,http://en.wikipedia.org/wiki/Silverstone_Circuit,Silverstone Circuit,52.0786,-1.01694,Silverstone,UK
17,spa,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...,Circuit de Spa-Francorchamps,50.4372,5.97139,Spa,Belgium
18,suzuka,http://en.wikipedia.org/wiki/Suzuka_Circuit,Suzuka Circuit,34.8431,136.54100,Suzuka,Japan
19,villeneuve,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...,Circuit Gilles Villeneuve,45.5000,-73.52280,Montreal,Canada
20,yas_marina,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,Yas Marina Circuit,24.4672,54.60310,Abu Dhabi,UAE
21,zandvoort,http://en.wikipedia.org/wiki/Circuit_Zandvoort,Circuit Park Zandvoort,52.3888,4.54092,Zandvoort,Netherlands

In [269]:
#Limpiamos el dataframe de circuitos
print("Circuitos disponibles: ")
circuitos = circuitos.drop(['url', 'Location/lat', 'Location/long', 'Location/locality'], axis = 1)
print(circuitos['Location/country'].to_string(index=False))
nombreCircuito = input("Introduce el pais de un Gran Premio: ")
anyoGp = 2020

Circuitos disponibles:
   Australia
         USA
     Bahrain
  Azerbaijan
       Spain
     Hungary
       Italy
      Brazil
Saudi Arabia
   Singapore
         USA
      Monaco
       Italy
     Austria
      France
      Mexico
          UK
     Belgium
       Japan
      Canada
         UAE
 Netherlands
Introduce el pais de un Gran Premio: Italy

In [270]:
#Creamos un nuevo dataframe con el nombre, la localidad y el nivel de desgaste que pueden tener los neumaticos
circuitos_desgaste = circuitos.drop(['circuitId'], axis=1)
circuitos_desgaste

                       circuitName Location/country
0   Albert Park Grand Prix Circuit        Australia
1          Circuit of the Americas              USA
2    Bahrain International Circuit          Bahrain
3                Baku City Circuit       Azerbaijan
4   Circuit de Barcelona-Catalunya            Spain
5                      Hungaroring          Hungary
6    Autodromo Enzo e Dino Ferrari            Italy
7       Autódromo José Carlos Pace           Brazil
8          Jeddah Corniche Circuit     Saudi Arabia
9        Marina Bay Street Circuit        Singapore
10   Miami International Autodrome              USA
11               Circuit de Monaco           Monaco
12    Autodromo Nazionale di Monza            Italy
13                   Red Bull Ring          Austria
14             Circuit Paul Ricard           France
15    Autódromo Hermanos Rodríguez           Mexico
16             Silverstone Circuit               UK
17    Circuit de Spa-Francorchamps          Belgium
18                  Suzuka Circuit            Japan
19       Circuit Gilles Villeneuve           Canada
20              Yas Marina Circuit              UAE
21          Circuit Park Zandvoort      Netherlands

In [271]:
#Creamos una lista con el nivel de desgaste, fuente PIRELLI F1 2022
desgaste = ['Bajo', 'Alto', 'Alto', 'Bajo', 'Alto', 'Bajo', 'Medio', 'Medio', 'Bajo', 'Bajo', 'Bajo', 'Medio', 'Medio', 'Medio', 'Medio', 'Bajo', 'Medio', 'Alto', 'Medio', 'Bajo', 'Medio', 'Medio']
circuitos_desgaste['desgaste'] = desgaste
circuitos_desgaste
vueltas_circuito = ['58', '56', '57', '51', '66', '70', '63', '71', '50', '61', '57', '78', '53', '71', '53', '71', '52', '44', '53', '70', '58', '72']
circuitos_desgaste['vueltas_totales'] = vueltas_circuito
circuitos_desgaste
km_circuito = ['307.574', '308.405', '308.238', '306.049', '307.104', '306.630', '309.049', '305.879', '308.450', '308.706', '308.326', '260.286', '306.720', '306.452', '309.690', '305.354', '306.198', '308.052', '307.471', '305.270', '305.355', '306.648']
circuitos_desgaste['km_total'] = km_circuito
circuitos_desgaste

#Vamos a sacarlo en un csv
#circuitos_desgaste.to_csv("../circuits/circuitosFinal.csv", index=False)

,circuitName,Location/country,desgaste,vueltas_totales,km_total
0,Albert Park Grand Prix Circuit,Australia,Bajo,58,307.574
1,Circuit of the Americas,USA,Alto,56,308.405
2,Bahrain International Circuit,Bahrain,Alto,57,308.238
3,Baku City Circuit,Azerbaijan,Bajo,51,306.049
4,Circuit de Barcelona-Catalunya,Spain,Alto,66,307.104
5,Hungaroring,Hungary,Bajo,70,306.630
6,Autodromo Enzo e Dino Ferrari,Italy,Medio,63,309.049
7,Autódromo José Carlos Pace,Brazil,Medio,71,305.879
8,Jeddah Corniche Circuit,Saudi Arabia,Bajo,50,308.450
9,Marina Bay Street Circuit,Singapore,Bajo,61,308.706
10,Miami International Autodrome,USA,Bajo,57,308.326
11,Circuit de Monaco,Monaco,Medio,78,260.286
12,Autodromo Nazionale di Monza,Italy,Medio,53,306.720
13,Red Bull Ring,Austria,Medio,71,306.452
14,Circuit Paul Ricard,France,Medio,53,309.690
15,Autódromo Hermanos Rodríguez,Mexico,Bajo,71,305.354
16,Silverstone Circuit,UK,Medio,52,306.198
17,Circuit de Spa-Francorchamps,Belgium,Alto,44,308.052
18,Suzuka Circuit,Japan,Medio,53,307.471
19,Circuit Gilles Villeneuve,Canada,Bajo,70,305.270
20,Yas Marina Circuit,UAE,Medio,58,305.355
21,Circuit Park Zandvoort,Netherlands,Medio,72,306.648

In [272]:
#Vamos entonces a crear un dataframe para un piloto en una determinada 
#carrera, por ejemplo, Fernando Alonso y Monaco 2022
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) #Omitimos los future warning

fastf1.Cache.enable_cache('../cache') # Para cachear los datos y no tener que bajarlos todo el tiempo

#A continuacion, nos guardamos la sesión en una variable de tipo sesion

race = fastf1.get_session(anyoGp, nombreCircuito, 'R')
race.load(weather=True, telemetry= True)

core           INFO 	Loading data for Italian Grand Prix - Race [v2.3.0]
api            INFO 	Using cached data for driver_info
api            INFO 	Using cached data for timing_data
api            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
api            INFO 	Using cached data for session_status_data
api            INFO 	Using cached data for track_status_data
api            INFO 	Using cached data for car_data
api            INFO 	Using cached data for position_data
api            INFO 	Using cached data for weather_data
api            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['10', '55', '18', '4', '77', '3', '44', '31', '26', '11', '6', '8', '7', '63', '23', '99', '33', '16', '20', '5']

In [273]:
print("Pilotos disponibles: ")
race.results['Abbreviation']
print(race.results['Abbreviation'].to_string(index=False))
nombrePiloto = input("Introduce un piloto: ")

Pilotos disponibles:
GAS
SAI
STR
NOR
BOT
RIC
HAM
OCO
KVY
PER
LAT
GRO
RAI
RUS
ALB
GIO
VER
LEC
MAG
VET
Introduce un piloto: LEC

In [274]:


#Creamos un diccionario para tener los nombres de los pilotos en Ergast y en FastF1 (para poder sacar la posicion por cada vuelta)
#ya que la api tiene la pinta del valor y fastf1 tiene la pinta de la clave (en el diccionario)
pilotosDic = {"HAM":"hamilton", "VER":"max_verstappen", "BOT": "bottas", "NOR":"norris", "PER":"perez", "LEC":"leclerc",
             "RIC":"ricciardo", "SAI":"sainz", "TSU":"tsunoda", "STR":"stroll", "RAI":"raikkonen", "GIO":"giovinazi",
              "OCO":"ocon", "RUS":"russel", "VET":"vettel", "MSC":"mick_schumacher", "GAS":"GASLY", "LAT":"latifi",
             "ALO":"alonso", "MAZ":"mazepin"}
print(pilotosDic[nombrePiloto])

leclerc

In [275]:
#Nos interesa saber el numero de vueltas que dio Alonso en Barcelona 2022


laps_race_pilot = race.laps.pick_driver(nombrePiloto)
weather = race.weather_data # Cogemos tambien el tiempo que hizo al inicio de la carrera
weather

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:33.270000,27.8,40.0,991.4,False,45.2,199,2.3
1,0 days 00:01:33.271000,28.0,39.0,991.4,False,45.1,159,2.5
2,0 days 00:02:33.287000,27.8,39.5,991.5,False,44.8,233,1.4
3,0 days 00:03:33.288000,27.5,40.4,991.4,False,44.3,151,0.7
4,0 days 00:04:33.288000,27.6,40.8,991.5,False,44.3,167,1.1
...,...,...,...,...,...,...,...,...
138,0 days 02:18:33.642000,27.8,41.9,990.4,False,36.2,169,1.4
139,0 days 02:19:33.642000,27.8,41.9,990.3,False,36.2,198,2.0
140,0 days 02:20:33.648000,27.7,41.9,990.3,False,36.2,158,1.8
141,0 days 02:21:33.643000,27.6,42.0,990.4,False,36.1,162,1.6
142,0 days 02:22:33.646000,27.6,42.3,990.3,False,35.8,169,1.7

In [276]:
laps_race_pilot

,Time,DriverNumber,LapTime,LapNumber,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,...,Compound,TyreLife,FreshTyre,Stint,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
878,0 days 00:35:02.290000,16,NaT,1,0 days 00:00:06.745000,NaT,NaT,0 days 00:00:31.401000,0 days 00:00:29.872000,NaT,...,SOFT,1.0,True,1,0 days 00:33:28.079000,Ferrari,LEC,1,False,2020-09-06 13:13:28.275
879,0 days 00:36:30.293000,16,0 days 00:01:28.003000,2,NaT,NaT,0 days 00:00:28.624000,0 days 00:00:30.253000,0 days 00:00:29.126000,0 days 00:35:30.914000,...,SOFT,2.0,True,1,0 days 00:35:02.290000,Ferrari,LEC,1,True,2020-09-06 13:15:02.486
880,0 days 00:37:57.218000,16,0 days 00:01:26.925000,3,NaT,NaT,0 days 00:00:28.327000,0 days 00:00:29.620000,0 days 00:00:28.978000,0 days 00:36:58.620000,...,SOFT,3.0,True,1,0 days 00:36:30.293000,Ferrari,LEC,1,True,2020-09-06 13:16:30.489
881,0 days 00:39:23.841000,16,0 days 00:01:26.623000,4,NaT,NaT,0 days 00:00:28.131000,0 days 00:00:29.662000,0 days 00:00:28.830000,0 days 00:38:25.349000,...,SOFT,4.0,True,1,0 days 00:37:57.218000,Ferrari,LEC,1,True,2020-09-06 13:17:57.414
882,0 days 00:40:50.195000,16,0 days 00:01:26.354000,5,NaT,NaT,0 days 00:00:28.163000,0 days 00:00:29.327000,0 days 00:00:28.864000,0 days 00:39:52.004000,...,SOFT,5.0,True,1,0 days 00:39:23.841000,Ferrari,LEC,1,True,2020-09-06 13:19:24.037
883,0 days 00:42:16.740000,16,0 days 00:01:26.545000,6,NaT,NaT,0 days 00:00:28.118000,0 days 00:00:29.582000,0 days 00:00:28.845000,0 days 00:41:18.313000,...,SOFT,6.0,True,1,0 days 00:40:50.195000,Ferrari,LEC,1,True,2020-09-06 13:20:50.391
884,0 days 00:43:43.267000,16,0 days 00:01:26.527000,7,NaT,NaT,0 days 00:00:28.151000,0 days 00:00:29.422000,0 days 00:00:28.954000,0 days 00:42:44.891000,...,SOFT,7.0,True,1,0 days 00:42:16.740000,Ferrari,LEC,1,True,2020-09-06 13:22:16.936
885,0 days 00:45:09.890000,16,0 days 00:01:26.623000,8,NaT,NaT,0 days 00:00:28.126000,0 days 00:00:29.450000,0 days 00:00:29.047000,0 days 00:44:11.393000,...,SOFT,8.0,True,1,0 days 00:43:43.267000,Ferrari,LEC,2,True,2020-09-06 13:23:43.463
886,0 days 00:46:36.642000,16,0 days 00:01:26.752000,9,NaT,NaT,0 days 00:00:28.257000,0 days 00:00:29.534000,0 days 00:00:28.961000,0 days 00:45:38.147000,...,SOFT,9.0,True,1,0 days 00:45:09.890000,Ferrari,LEC,1,True,2020-09-06 13:25:10.086
887,0 days 00:48:03.047000,16,0 days 00:01:26.405000,10,NaT,NaT,0 days 00:00:28.083000,0 days 00:00:29.475000,0 days 00:00:28.847000,0 days 00:47:04.725000,...,SOFT,10.0,True,1,0 days 00:46:36.642000,Ferrari,LEC,1,True,2020-09-06 13:26:36.838
888,0 days 00:49:29.456000,16,0 days 00:01:26.409000,11,NaT,NaT,0 days 00:00:28.078000,0 days 00:00:29.442000,0 days 00:00:28.889000,0 days 00:48:31.125000,...,SOFT,11.0,True,1,0 days 00:48:03.047000,Ferrari,LEC,1,True,2020-09-06 13:28:03.243
889,0 days 00:50:55.833000,16,0 days 00:01:26.377000,12,NaT,NaT,0 days 00:00:28.099000,0 days 00:00:29.363000,0 days 00:00:28.915000,0 days 00:49:57.555000,...,SOFT,12.0,True,1,0 days 00:49:29.456000,Ferrari,LEC,1,True,2020-09-06 13:29:29.652
890,0 days 00:52:22.390000,16,0 days 00:01:26.557000,13,NaT,NaT,0 days 00:00:28.134000,0 days 00:00:29.490000,0 days 00:00:28.933000,0 days 00:51:23.967000,...,SOFT,13.0,True,1,0 days 00:50:55.833000,Ferrari,LEC,1,True,2020-09-06 13:30:56.029
891,0 days 00:53:49.099000,16,0 days 00:01:26.709000,14,NaT,NaT,0 days 00:00:28.193000,0 days 00:00:29.489000,0 days 00:00:29.027000,0 days 00:52:50.583000,...,SOFT,14.0,True,1,0 days 00:52:22.390000,Ferrari,LEC,1,True,2020-09-06 13:32:22.586
892,0 days 00:55:15.820000,16,0 days 00:01:26.721000,15,NaT,NaT,0 days 00:00:28.198000,0 days 00:00:29.506000,0 days 00:00:29.017000,0 days 00:54:17.297000,...,SOFT,15.0,True,1,0 days 00:53:49.099000,Ferrari,LEC,1,True,2020-09-06 13:33:49.295
893,0 days 00:56:42.599000,16,0 days 00:01:26.779000,16,NaT,NaT,0 days 00:00:28.185000,0 days 00:00:29.576000,0 days 00:00:29.018000,0 days 00:55:44.005000,...,SOFT,16.0,True,1,0 days 00:55:15.820000,Ferrari,LEC,1,True,2020-09-06 13:35:16.016
894,0 days 00:58:15.929000,16,0 days 00:01:33.330000,17,NaT,0 days 00:58:12.218000,0 days 00:00:28.336000,0 days 00:00:31.630000,0 days 00:00:33.364000,0 days 00:57:10.935000,...,SOFT,17.0,True,1,0 days 00:56:42.599000,Ferrari,LEC,1,False,2020-09-06 13:36:42.795
895,0 days 01:00:03.340000,16,0 days 00:01:47.411000,18,0 days 00:58:36.566000,NaT,0 days 00:00:49.365000,0 days 00:00:29.575000,0 days 00:00:28.471000,0 days 00:59:05.294000,...,HARD,1.0,True,2,0 days 00:58:15.929000,Ferrari,LEC,1,False,2020-09-06 13:38:16.125
896,0 days 01:01:29.366000,16,0 days 00:01:26.026000,19,NaT,NaT,0 days 00:00:28.226000,0 days 00:00:28.950000,0 days 00:00:28.850000,0 days 01:00:31.566000,...,HARD,2.0,True,2,0 days 01:00:03.340000,Ferrari,LEC,2,True,2020-09-06 13:40:03.536
897,0 days 01:03:25.299000,16,0 days 00:01:55.933000,20,NaT,NaT,0 days 00:00:35.484000,0 days 00:00:40.142000,0 days 00:00:40.307000,0 days 01:02:04.850000,...,HARD,3.0,True,2,0 days 01:01:29.366000,Ferrari,LEC,24,False,2020-09-06 13:41:29.562
898,0 days 01:05:22.705000,16,0 days 00:01:57.406000,21,NaT,NaT,0 days 00:00:37.068000,0 days 00:00:39.170000,0 days 00:00:41.168000,0 days 01:04:02.367000,...,HARD,4.0,True,2,0 days 01:03:25.299000,Ferrari,LEC,4,False,2020-09-06 13:43:25.495
899,0 days 01:07:00.319000,16,0 days 00:01:37.614000,22,NaT,NaT,0 days 00:00:31.557000,0 days 00:00:29.509000,0 days 00:00:36.548000,0 days 01:05:54.262000,...,HARD,5.0,True,2,0 days 01:05:22.705000,Ferrari,LEC,4,False,2020-09-06 13:45:22.901
900,0 days 01:08:55.897000,16,0 days 00:01:55.578000,23,NaT,NaT,0 days 00:00:32.440000,0 days 00:00:37.028000,0 days 00:00:46.110000,0 days 01:07:32.759000,...,HARD,6.0,True,2,0 days 01:07:00.319000,Ferrari,LEC,4,False,2020-09-06 13:47:00.515
901,0 days 01:27:17.699000,16,NaT,24,0 days 01:27:39.119000,0 days 01:27:17.699000,0 days 00:00:27.926000,0 days 00:00:29.443000,NaT,0 days 01:09:23.898000,...,HARD,7.0,True,2,0 days 01:08:55.897000,Ferrari,LEC,245,False,2020-09-06 13:48:56.093

In [277]:
#Limpiamos el dataset con solo lo que nos interesa

laps_race_pilot = laps_race_pilot.filter(['Time', 'LapTime', 'LapNumber', 'Compound', 'TyreLife', 'FreshTyre', 'TrackStatus', 'Stint', 'PitInTime'])
laps_race_pilot

,Time,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime
878,0 days 00:35:02.290000,NaT,1,SOFT,1.0,True,1,1,NaT
879,0 days 00:36:30.293000,0 days 00:01:28.003000,2,SOFT,2.0,True,1,1,NaT
880,0 days 00:37:57.218000,0 days 00:01:26.925000,3,SOFT,3.0,True,1,1,NaT
881,0 days 00:39:23.841000,0 days 00:01:26.623000,4,SOFT,4.0,True,1,1,NaT
882,0 days 00:40:50.195000,0 days 00:01:26.354000,5,SOFT,5.0,True,1,1,NaT
883,0 days 00:42:16.740000,0 days 00:01:26.545000,6,SOFT,6.0,True,1,1,NaT
884,0 days 00:43:43.267000,0 days 00:01:26.527000,7,SOFT,7.0,True,1,1,NaT
885,0 days 00:45:09.890000,0 days 00:01:26.623000,8,SOFT,8.0,True,2,1,NaT
886,0 days 00:46:36.642000,0 days 00:01:26.752000,9,SOFT,9.0,True,1,1,NaT
887,0 days 00:48:03.047000,0 days 00:01:26.405000,10,SOFT,10.0,True,1,1,NaT
888,0 days 00:49:29.456000,0 days 00:01:26.409000,11,SOFT,11.0,True,1,1,NaT
889,0 days 00:50:55.833000,0 days 00:01:26.377000,12,SOFT,12.0,True,1,1,NaT
890,0 days 00:52:22.390000,0 days 00:01:26.557000,13,SOFT,13.0,True,1,1,NaT
891,0 days 00:53:49.099000,0 days 00:01:26.709000,14,SOFT,14.0,True,1,1,NaT
892,0 days 00:55:15.820000,0 days 00:01:26.721000,15,SOFT,15.0,True,1,1,NaT
893,0 days 00:56:42.599000,0 days 00:01:26.779000,16,SOFT,16.0,True,1,1,NaT
894,0 days 00:58:15.929000,0 days 00:01:33.330000,17,SOFT,17.0,True,1,1,0 days 00:58:12.218000
895,0 days 01:00:03.340000,0 days 00:01:47.411000,18,HARD,1.0,True,1,2,NaT
896,0 days 01:01:29.366000,0 days 00:01:26.026000,19,HARD,2.0,True,2,2,NaT
897,0 days 01:03:25.299000,0 days 00:01:55.933000,20,HARD,3.0,True,24,2,NaT
898,0 days 01:05:22.705000,0 days 00:01:57.406000,21,HARD,4.0,True,4,2,NaT
899,0 days 01:07:00.319000,0 days 00:01:37.614000,22,HARD,5.0,True,4,2,NaT
900,0 days 01:08:55.897000,0 days 00:01:55.578000,23,HARD,6.0,True,4,2,NaT
901,0 days 01:27:17.699000,NaT,24,HARD,7.0,True,245,2,0 days 01:27:17.699000

In [278]:
#De aqui solo queremos la temperatura de la pista, la temperatura ambiente y si llovía o no 
#Importante, hacemos match de la columna time, o ponemos simplemente el tiempo que hacia en la salida????
weather = weather.filter(['Time', 'AirTemp', 'Humidity', 'Rainfall', 'TrackTemp'])
weather

                      Time  AirTemp  Humidity  Rainfall  TrackTemp
0   0 days 00:00:33.270000     27.8      40.0     False       45.2
1   0 days 00:01:33.271000     28.0      39.0     False       45.1
2   0 days 00:02:33.287000     27.8      39.5     False       44.8
3   0 days 00:03:33.288000     27.5      40.4     False       44.3
4   0 days 00:04:33.288000     27.6      40.8     False       44.3
..                     ...      ...       ...       ...        ...
138 0 days 02:18:33.642000     27.8      41.9     False       36.2
139 0 days 02:19:33.642000     27.8      41.9     False       36.2
140 0 days 02:20:33.648000     27.7      41.9     False       36.2
141 0 days 02:21:33.643000     27.6      42.0     False       36.1
142 0 days 02:22:33.646000     27.6      42.3     False       35.8

[143 rows x 5 columns]

In [279]:
weather['Time'] = weather['Time'].astype(str)
weather

                       Time  AirTemp  Humidity  Rainfall  TrackTemp
0    0 days 00:00:33.270000     27.8      40.0     False       45.2
1    0 days 00:01:33.271000     28.0      39.0     False       45.1
2    0 days 00:02:33.287000     27.8      39.5     False       44.8
3    0 days 00:03:33.288000     27.5      40.4     False       44.3
4    0 days 00:04:33.288000     27.6      40.8     False       44.3
..                      ...      ...       ...       ...        ...
138  0 days 02:18:33.642000     27.8      41.9     False       36.2
139  0 days 02:19:33.642000     27.8      41.9     False       36.2
140  0 days 02:20:33.648000     27.7      41.9     False       36.2
141  0 days 02:21:33.643000     27.6      42.0     False       36.1
142  0 days 02:22:33.646000     27.6      42.3     False       35.8

[143 rows x 5 columns]

In [280]:
#Modificamos la columna de Time, para que solo nos muestre la hora y el minuto, esto es para
#que casen las keys al hacer el join y podamos tener info de la temperatura minuto a minuto en las vueltas
weather['Time'] = weather["Time"].apply(lambda x: x[7:12])
weather

      Time  AirTemp  Humidity  Rainfall  TrackTemp
0    00:00     27.8      40.0     False       45.2
1    00:01     28.0      39.0     False       45.1
2    00:02     27.8      39.5     False       44.8
3    00:03     27.5      40.4     False       44.3
4    00:04     27.6      40.8     False       44.3
..     ...      ...       ...       ...        ...
138  02:18     27.8      41.9     False       36.2
139  02:19     27.8      41.9     False       36.2
140  02:20     27.7      41.9     False       36.2
141  02:21     27.6      42.0     False       36.1
142  02:22     27.6      42.3     False       35.8

[143 rows x 5 columns]

In [281]:
#Hacemos lo mismo para la columa Time de las vueltas
laps_race_pilot['Time'] = laps_race_pilot['Time'].astype(str)
laps_race_pilot['Time'] = laps_race_pilot["Time"].apply(lambda x: x[7:12])
laps_race_pilot

,Time,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime
878,00:35,NaT,1,SOFT,1.0,True,1,1,NaT
879,00:36,0 days 00:01:28.003000,2,SOFT,2.0,True,1,1,NaT
880,00:37,0 days 00:01:26.925000,3,SOFT,3.0,True,1,1,NaT
881,00:39,0 days 00:01:26.623000,4,SOFT,4.0,True,1,1,NaT
882,00:40,0 days 00:01:26.354000,5,SOFT,5.0,True,1,1,NaT
883,00:42,0 days 00:01:26.545000,6,SOFT,6.0,True,1,1,NaT
884,00:43,0 days 00:01:26.527000,7,SOFT,7.0,True,1,1,NaT
885,00:45,0 days 00:01:26.623000,8,SOFT,8.0,True,2,1,NaT
886,00:46,0 days 00:01:26.752000,9,SOFT,9.0,True,1,1,NaT
887,00:48,0 days 00:01:26.405000,10,SOFT,10.0,True,1,1,NaT
888,00:49,0 days 00:01:26.409000,11,SOFT,11.0,True,1,1,NaT
889,00:50,0 days 00:01:26.377000,12,SOFT,12.0,True,1,1,NaT
890,00:52,0 days 00:01:26.557000,13,SOFT,13.0,True,1,1,NaT
891,00:53,0 days 00:01:26.709000,14,SOFT,14.0,True,1,1,NaT
892,00:55,0 days 00:01:26.721000,15,SOFT,15.0,True,1,1,NaT
893,00:56,0 days 00:01:26.779000,16,SOFT,16.0,True,1,1,NaT
894,00:58,0 days 00:01:33.330000,17,SOFT,17.0,True,1,1,0 days 00:58:12.218000
895,01:00,0 days 00:01:47.411000,18,HARD,1.0,True,1,2,NaT
896,01:01,0 days 00:01:26.026000,19,HARD,2.0,True,2,2,NaT
897,01:03,0 days 00:01:55.933000,20,HARD,3.0,True,24,2,NaT
898,01:05,0 days 00:01:57.406000,21,HARD,4.0,True,4,2,NaT
899,01:07,0 days 00:01:37.614000,22,HARD,5.0,True,4,2,NaT
900,01:08,0 days 00:01:55.578000,23,HARD,6.0,True,4,2,NaT
901,01:27,NaT,24,HARD,7.0,True,245,2,0 days 01:27:17.699000

In [282]:
#Hacemos el join para meter en el mismo dataset, la imformacion en cada vuelta de la temperatura ambiente y de la pista

laps_race_pilot = laps_race_pilot.set_index('Time').join(weather.set_index('Time'))

In [283]:
laps_race_pilot['LapTime'] = laps_race_pilot['LapTime'].astype(str)
laps_race_pilot["LapTime"] = laps_race_pilot["LapTime"].apply(lambda x: x[10:19] if x!="NaT" else '0')
laps_race_pilot

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime,AirTemp,Humidity,Rainfall,TrackTemp
Time,,,,,,,,,,,,
00:35,0,1,SOFT,1.0,True,1,1,NaT,27.6,41.6,False,43.9
00:36,01:28.003,2,SOFT,2.0,True,1,1,NaT,27.8,39.7,False,44.0
00:37,01:26.925,3,SOFT,3.0,True,1,1,NaT,27.9,39.9,False,44.2
00:39,01:26.623,4,SOFT,4.0,True,1,1,NaT,28.3,39.7,False,45.0
00:40,01:26.354,5,SOFT,5.0,True,1,1,NaT,28.0,40.0,False,44.7
00:42,01:26.545,6,SOFT,6.0,True,1,1,NaT,28.1,40.5,False,44.3
00:43,01:26.527,7,SOFT,7.0,True,1,1,NaT,28.2,39.9,False,43.9
00:45,01:26.623,8,SOFT,8.0,True,2,1,NaT,28.3,40.3,False,43.6
00:46,01:26.752,9,SOFT,9.0,True,1,1,NaT,28.2,41.0,False,43.7
00:48,01:26.405,10,SOFT,10.0,True,1,1,NaT,28.5,39.4,False,43.7
00:49,01:26.409,11,SOFT,11.0,True,1,1,NaT,27.9,40.8,False,43.7
00:50,01:26.377,12,SOFT,12.0,True,1,1,NaT,27.7,41.2,False,43.8
00:52,01:26.557,13,SOFT,13.0,True,1,1,NaT,28.2,40.3,False,44.2
00:53,01:26.709,14,SOFT,14.0,True,1,1,NaT,28.2,40.7,False,44.1
00:55,01:26.721,15,SOFT,15.0,True,1,1,NaT,27.9,40.6,False,43.5
00:56,01:26.779,16,SOFT,16.0,True,1,1,NaT,27.7,41.7,False,43.6
00:58,01:33.330,17,SOFT,17.0,True,1,1,0 days 00:58:12.218000,27.8,41.2,False,44.2
01:00,01:47.411,18,HARD,1.0,True,1,2,NaT,27.5,40.6,False,43.8
01:01,01:26.026,19,HARD,2.0,True,2,2,NaT,27.5,41.2,False,43.6
01:03,01:55.933,20,HARD,3.0,True,24,2,NaT,27.9,40.7,False,43.6
01:05,01:57.406,21,HARD,4.0,True,4,2,NaT,27.8,40.6,False,43.9
01:07,01:37.614,22,HARD,5.0,True,4,2,NaT,27.7,41.4,False,43.9
01:08,01:55.578,23,HARD,6.0,True,4,2,NaT,28.1,40.4,False,43.7
01:27,0,24,HARD,7.0,True,245,2,0 days 01:27:17.699000,28.8,39.2,False,40.3

In [284]:
#Para la posicion de salida
#posicion_salida = race.get_driver(nombrePiloto)['GridPosition']
#posicion_salida
race.get_driver(nombrePiloto)

DriverNumber                  16
BroadcastName          C LECLERC
Abbreviation                 LEC
TeamName                 Ferrari
TeamColor                 DC0000
FirstName                Charles
LastName                 Leclerc
FullName         Charles Leclerc
Position                    18.0
GridPosition                13.0
Q1                           NaT
Q2                           NaT
Q3                           NaT
Time                         NaT
Status                  Accident
Points                       0.0
Name: Charles, dtype: object

In [285]:
#Necesitamos ahora los outputs, que es la siguiente vuelta a parar
vueltas_parada = laps_race_pilot[laps_race_pilot['PitInTime'].notna()]
vueltas_parada

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,PitInTime,AirTemp,Humidity,Rainfall,TrackTemp
Time,,,,,,,,,,,,
00:58,01:33.330,17,SOFT,17.0,True,1,1,0 days 00:58:12.218000,27.8,41.2,False,44.2
01:27,0,24,HARD,7.0,True,245,2,0 days 01:27:17.699000,28.8,39.2,False,40.3

In [286]:
nVuelta_parada = vueltas_parada['LapNumber']
nParadas = 0
paradas = []
for i in nVuelta_parada:
    paradas.append(i)
    nParadas = nParadas + 1


print("El numero de paradas ha sido: ", nParadas)

print("Las paradas han sido en las vueltas: ", paradas)

El numero de paradas ha sido:  2
Las paradas han sido en las vueltas:  [17, 24]

In [287]:
#Eliminanos la variable de la hora a la que entra a box porque ya no es necesaria
laps_race_pilot.drop(['PitInTime'], axis = 1, inplace=True)
#laps_race_pilot.drop(laps_race_pilot[(laps_race_pilot['LapTime'] =='0') & (laps_race_pilot['LapNumber'] != 1)].index, inplace=True)
laps_race_pilot

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,AirTemp,Humidity,Rainfall,TrackTemp
Time,,,,,,,,,,,
00:35,0,1,SOFT,1.0,True,1,1,27.6,41.6,False,43.9
00:36,01:28.003,2,SOFT,2.0,True,1,1,27.8,39.7,False,44.0
00:37,01:26.925,3,SOFT,3.0,True,1,1,27.9,39.9,False,44.2
00:39,01:26.623,4,SOFT,4.0,True,1,1,28.3,39.7,False,45.0
00:40,01:26.354,5,SOFT,5.0,True,1,1,28.0,40.0,False,44.7
00:42,01:26.545,6,SOFT,6.0,True,1,1,28.1,40.5,False,44.3
00:43,01:26.527,7,SOFT,7.0,True,1,1,28.2,39.9,False,43.9
00:45,01:26.623,8,SOFT,8.0,True,2,1,28.3,40.3,False,43.6
00:46,01:26.752,9,SOFT,9.0,True,1,1,28.2,41.0,False,43.7
00:48,01:26.405,10,SOFT,10.0,True,1,1,28.5,39.4,False,43.7
00:49,01:26.409,11,SOFT,11.0,True,1,1,27.9,40.8,False,43.7
00:50,01:26.377,12,SOFT,12.0,True,1,1,27.7,41.2,False,43.8
00:52,01:26.557,13,SOFT,13.0,True,1,1,28.2,40.3,False,44.2
00:53,01:26.709,14,SOFT,14.0,True,1,1,28.2,40.7,False,44.1
00:55,01:26.721,15,SOFT,15.0,True,1,1,27.9,40.6,False,43.5
00:56,01:26.779,16,SOFT,16.0,True,1,1,27.7,41.7,False,43.6
00:58,01:33.330,17,SOFT,17.0,True,1,1,27.8,41.2,False,44.2
01:00,01:47.411,18,HARD,1.0,True,1,2,27.5,40.6,False,43.8
01:01,01:26.026,19,HARD,2.0,True,2,2,27.5,41.2,False,43.6
01:03,01:55.933,20,HARD,3.0,True,24,2,27.9,40.7,False,43.6
01:05,01:57.406,21,HARD,4.0,True,4,2,27.8,40.6,False,43.9
01:07,01:37.614,22,HARD,5.0,True,4,2,27.7,41.4,False,43.9
01:08,01:55.578,23,HARD,6.0,True,4,2,28.1,40.4,False,43.7
01:27,0,24,HARD,7.0,True,245,2,28.8,39.2,False,40.3

In [288]:
nVueltasDadas = int(laps_race_pilot.tail(1)['LapNumber'].iloc[0])
nVueltasDadas

24

In [289]:
#Ahora hay que añadir al dataframe las variables
# - Posicion de salida
# - Siguiente parada (dependera de la vuelta en la que se encuentre)
# - Todas variables del circuito en el que nos encontramos, en este caso Barcelona
# - No creo que haga falta el piloto, las estrategias son independientes del piloto (o eso voy a pensar... que no será asi)
circuito_actual = circuitos_desgaste.loc[circuitos_desgaste['Location/country'].str.lower() == nombreCircuito.lower()]
circuito_actual = circuito_actual.filter(['circuitName', 'desgaste', 'vueltas_totales', 'km_total'])
circuito_actual
vueltasOficialesCircuito = circuito_actual['vueltas_totales'].iloc[0]
print(vueltasOficialesCircuito)
print(nVueltasDadas)
disminuido = False

if (str(nVueltasDadas) == vueltasOficialesCircuito):
    nVueltasDadas = nVueltasDadas -1
    disminuido = True

print("Las vueltas son: " + str(nVueltasDadas))

63
24
Las vueltas son: 24

In [290]:
#Ahora hay que introducir la columna posicionActual que es la posicion que ocupa un piloto por cada paso por meta3#
#para cada una de las vueltas que un piloto dio en un determinado gran premio
#Para elllo hay que construir la llamada a la API de Ergast, que tiene esta pinta:
# http://ergast.com/api/f1/2022/1/drivers/alonso/laps/19
#Necesitamos el numero de ronda, el año del gp, el numero de vuelta y el nombre del piloto
import requests
import json
import time
roundNumber = race.event.RoundNumber
pilotoNombre=pilotosDic[nombrePiloto]
posicionesList = []
pilotoDelanteList = []
tiempoPilotoDelanteList = []
pilotoDetrasList = []
tiempoPilotoDetrasList = []


#Llamada a api de posiciones
api = "http://ergast.com/api/f1/" + str(anyoGp) + "/" + str(roundNumber) + "/drivers/" +pilotoNombre + "/laps.json?limit=100"
response = requests.get(api)
posiciones_dict = json.loads(response.text)
#Llamada a api de pilotos y tiempo
api = "http://ergast.com/api/f1/" + str(anyoGp) + "/" + str(roundNumber) + "/" + "laps.json?limit=4000"
response = requests.get(api)
pilotos_dict = json.loads(response.text)
    
#El numero de vuelta es una iteracion a cada fila dell dataframe de vueltas del piloto

for nVuelta in range (0, nVueltasDadas):
    print(nVuelta, nVueltasDadas)
    #Para la posicion por cada vuelta
    posicion = posiciones_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][0]['position']
    posicionesList.append(posicion)

    #Para el piloto de delante y su tiempo en cada vuelta
    pilotoDelante = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)-2]['driverId']
    tiempoPilotoDelante = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)-2]['time']
    pilotoDelanteList.append(pilotoDelante)
    tiempoPilotoDelanteList.append(tiempoPilotoDelante)
    print("Voy el: ", posicion)  
    print("Tengo delante a : ", pilotoDelante)  

    #Para el piloto de detras y su tiempo en cada vuelta
    pilotoDetras = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)]['driverId']
    tiempoPilotoDetras = pilotos_dict['MRData']['RaceTable']['Races'][0]['Laps'][nVuelta]['Timings'][int(posicion)]['time']
    pilotoDetrasList.append(pilotoDetras)
    tiempoPilotoDetrasList.append(tiempoPilotoDetras)  
    print("Tengo detras a : ", pilotoDetras)  



if (disminuido):
    posicionesList.append("NaN")
    pilotoDelanteList.append("NaN")
    tiempoPilotoDelanteList.append("NaN")
    pilotoDetrasList.append("NaN")
    tiempoPilotoDetrasList.append("NaN")

laps_race_pilot['posicionActual'] = posicionesList
laps_race_pilot['pilotoDelante'] = pilotoDelanteList
laps_race_pilot['tiempoPilotoDelante'] = tiempoPilotoDelanteList
laps_race_pilot['pilotoDetras'] = pilotoDetrasList
laps_race_pilot['tiempoPilotoDetras'] = tiempoPilotoDetrasList

laps_race_pilot

0 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  giovinazzi
1 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  giovinazzi
2 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  giovinazzi
3 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
4 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
5 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
6 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
7 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
8 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
9 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
10 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
11 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
12 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
13 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
14 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
15 24
Voy el:  13
Tengo delante a :  raikkonen
Tengo detras a :  albon
16 24
Voy el:  16
Tengo delante a :  grosjean
Tengo detras a :  russell
17 24
Voy el:  17
Tengo delante a :  russell
Tengo detras a :  latifi
18 24
Voy el:  17
Tengo delante a :  raikkonen
Tengo detras a :  latifi
19 24
Voy el:  17
Tengo delante a :  raikkonen
Tengo detras a :  latifi
20 24
Voy el:  17
Tengo delante a :  raikkonen
Tengo detras a :  latifi
21 24
Voy el:  14
Tengo delante a :  kvyat
Tengo detras a :  albon
22 24
Voy el:  6
Tengo delante a :  raikkonen
Tengo detras a :  latifi
23 24

IndexError: list index out of range

In [261]:
roundNumber

8

In [262]:
#Hay que hacer una funcion para sacar el numero de vueltas (nVueltas) que se ha dado en ese circuito, y repetir nVueltas para crear una lista con el valor
nVueltasCircuito=laps_race_pilot.tail(1).LapNumber.values[0]
circuitName = circuito_actual.circuitName.values[0]
desgaste = circuito_actual.desgaste.values[0]
km_total = circuito_actual.km_total.values[0]
vueltas_totales = circuito_actual.vueltas_totales.values[0]
desgaste
print(nVueltasCircuito)

23

In [263]:
posicion_salida = race.get_driver(nombrePiloto)['GridPosition']

#La salida se la tenemos que meter a todas las filas del dataframe
laps_race_pilot['posicionSalida'] = posicion_salida
#laps_race_pilot['circuitName'] = circuitName
#laps_race_pilot['desgasteCircuito'] = desgaste
#laps_race_pilot['vueltasCircuito'] = vueltas_totales
#laps_race_pilot['kmCircuitoTotales'] = km_total

laps_race_pilot

,LapTime,LapNumber,Compound,TyreLife,FreshTyre,TrackStatus,Stint,AirTemp,Humidity,Rainfall,TrackTemp,posicionActual,pilotoDelante,tiempoPilotoDelante,pilotoDetras,tiempoPilotoDetras,posicionSalida
Time,,,,,,,,,,,,,,,,,
00:35,0,1,SOFT,1.0,True,1,1,27.6,41.6,False,43.9,13,raikkonen,1:33.635,giovinazzi,1:34.388,13.0
00:36,01:28.003,2,SOFT,2.0,True,1,1,27.8,39.7,False,44.0,13,raikkonen,1:27.629,giovinazzi,1:28.219,13.0
00:37,01:26.925,3,SOFT,3.0,True,1,1,27.9,39.9,False,44.2,13,raikkonen,1:26.820,giovinazzi,1:27.114,13.0
00:39,01:26.623,4,SOFT,4.0,True,1,1,28.3,39.7,False,45.0,13,raikkonen,1:26.318,albon,1:26.472,13.0
00:40,01:26.354,5,SOFT,5.0,True,1,1,28.0,40.0,False,44.7,13,raikkonen,1:26.468,albon,1:26.159,13.0
00:42,01:26.545,6,SOFT,6.0,True,1,1,28.1,40.5,False,44.3,13,raikkonen,1:26.218,albon,1:26.590,13.0
00:43,01:26.527,7,SOFT,7.0,True,1,1,28.2,39.9,False,43.9,13,raikkonen,1:26.331,albon,1:26.732,13.0
00:45,01:26.623,8,SOFT,8.0,True,2,1,28.3,40.3,False,43.6,13,raikkonen,1:26.453,albon,1:26.376,13.0
00:46,01:26.752,9,SOFT,9.0,True,1,1,28.2,41.0,False,43.7,13,raikkonen,1:26.418,albon,1:26.798,13.0
00:48,01:26.405,10,SOFT,10.0,True,1,1,28.5,39.4,False,43.7,13,raikkonen,1:26.110,albon,1:26.697,13.0
00:49,01:26.409,11,SOFT,11.0,True,1,1,27.9,40.8,False,43.7,13,raikkonen,1:26.404,albon,1:26.745,13.0
00:50,01:26.377,12,SOFT,12.0,True,1,1,27.7,41.2,False,43.8,13,raikkonen,1:26.215,albon,1:26.273,13.0
00:52,01:26.557,13,SOFT,13.0,True,1,1,28.2,40.3,False,44.2,13,raikkonen,1:26.387,albon,1:26.382,13.0
00:53,01:26.709,14,SOFT,14.0,True,1,1,28.2,40.7,False,44.1,13,raikkonen,1:26.189,albon,1:26.530,13.0
00:55,01:26.721,15,SOFT,15.0,True,1,1,27.9,40.6,False,43.5,13,raikkonen,1:26.291,albon,1:26.510,13.0
00:56,01:26.779,16,SOFT,16.0,True,1,1,27.7,41.7,False,43.6,13,raikkonen,1:26.492,albon,1:26.407,13.0
00:58,01:33.330,17,SOFT,17.0,True,1,1,27.8,41.2,False,44.2,16,grosjean,1:26.682,russell,1:26.560,13.0
01:00,01:47.411,18,HARD,1.0,True,1,2,27.5,40.6,False,43.8,17,russell,1:26.498,latifi,1:26.132,13.0
01:01,01:26.026,19,HARD,2.0,True,2,2,27.5,41.2,False,43.6,17,raikkonen,1:46.392,latifi,1:26.418,13.0
01:03,01:55.933,20,HARD,3.0,True,24,2,27.9,40.7,False,43.6,17,raikkonen,1:54.667,latifi,1:59.685,13.0
01:05,01:57.406,21,HARD,4.0,True,4,2,27.8,40.6,False,43.9,17,raikkonen,1:58.974,latifi,1:46.240,13.0
01:07,01:37.614,22,HARD,5.0,True,4,2,27.7,41.4,False,43.9,14,kvyat,2:14.530,albon,2:12.273,13.0
01:08,01:55.578,23,HARD,6.0,True,4,2,28.1,40.4,False,43.7,6,raikkonen,1:55.684,latifi,1:55.314,13.0

In [264]:
#Ahora hay que meter las paradas, habria que añadir una columna con la siguiente parada, dependiendo de la vuelta en la que se encuentre
paradas_list = paradas
paradas_list

[17, 24]

In [265]:
#En cada intervalo de ventana de parada, se añade la siguiente parada de acuerdo con el numero de vuelta en el que vamos
#Es decir, del intervalo 1-9, el valor de la siguiente parada es 10, del 10-30, el valor es 31, y así
#NOTA: Cuando se hace la ultima parada, ¿cual debe ser el valor del la siguiente parada? ¿El numero de fin de vuelta?


inserciones = 1
paradasList_insertar = []
for i in paradas_list:
        while (inserciones <= i):
            paradasList_insertar.append(i)
            inserciones = inserciones + 1
            if (inserciones == paradas_list[nParadas-1]):
                while inserciones < nVueltasCircuito:
                    paradasList_insertar.append(nVueltasCircuito)
                    inserciones = inserciones + 1
paradasList_insertar
len(paradasList_insertar)

24

In [266]:
#Insertamos la nueva columna
laps_race_pilot['nextPit'] = paradasList_insertar
laps_race_pilot

ValueError: Length of values (24) does not match length of index (23)

En principio, ahora tenemos el dataset para:

- Un piloto
- En un gran premio
- Durante todas sus vueltas

In [64]:
laps_race_pilot.to_csv("../datasets_completos/laps_" + nombreCircuito + "_" + nombrePiloto  +"_" +str(anyoGp)+ ".csv", index=False)